---
dist: xenial
sudo: required
language: python
services:
  - docker
matrix:
  fast_finish: true
python:
  - "2.7"
  - "3.7"

cache: pip

before_script:
  - cd ../
  - mv ansible-role-php-yaf daixijun.php-yaf
  - cd daixijun.php-yaf

install:
  - pip install ansible molecule docker

script:
  - molecule test

notifications:
  email: false
  webhooks:
    - https://galaxy.ansible.com/api/v1/notifications/
