---
# tasks file for daixijun.php-yaf
- name: Verify yaf extension is installed
  stat:
    path: "{{ ansible_local.php.extension_dir }}/yaf.so"
  register: yaf_installed_stat

- name: Check php yaf package is already exists
  stat:
    path: "{{ role_path }}/files/{{ php_yaf_download_url | basename }}"
  become: false
  run_once: true
  delegate_to: localhost
  register: _php_yaf_package_stat

- name: Download php yaf package
  get_url:
    url: "{{ php_yaf_download_url }}"
    dest: "{{ role_path }}/files/"
  become: false
  run_once: true
  delegate_to: localhost
  register: _php_yaf_package
  when:
    - not _php_yaf_package_stat.stat.exists
    - not yaf_installed_stat.stat.exists

- name: Unarchive php-yaf {{ php_yaf_version }}
  unarchive:
    src: "files/{{ php_yaf_download_url | basename }}"
    dest: /usr/local/src/
    remote_src: false
    creates: /usr/local/src/yaf-{{ php_yaf_version }}
  when:
    - not yaf_installed_stat.stat.exists and (_php_yaf_package is not skipped or _php_yaf_package_stat.stat.exists)

- name: Install
  command: "{{ item }}"
  args:
    chdir: "/usr/local/src/yaf-{{ php_yaf_version }}"
  loop:
    - /usr/local/php/bin/phpize
    - ./configure --enable-yaf --with-php-config=/usr/local/php/bin/php-config
    - make
    - make install
    - chown {{ ansible_local.php.web_user }}:{{ ansible_local.php.web_user }} {{ ansible_local.php.extension_dir }}/yaf.so
  when:
    - not yaf_installed_stat.stat.exists
  tags:
    - skip_ansible_lint

- name: Generate configuration file
  copy:
    content: "extension=yaf.so"
    dest: /usr/local/php/etc/php.d/yaf.ini
    mode: "644"
    owner: "{{ ansible_local.php.web_user }}"
    group: "{{ ansible_local.php.web_user }}"
  notify:
    - restart php-fpm

- name: Clean package
  file:
    path: "/usr/local/src/yaf-{{ php_yaf_version }}"
    state: absent
